apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-demo-secrets
  namespace: dapr-demo
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../dapr/components/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - publisher
  - subscriber
  - subscriber.state